version: "3"

services:

  database:
    image: postgres:11-alpine
    container_name: ${APP_NAME}_postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: "none"
    networks:
      - wikijs

  wiki:
    image: requarks/wiki:2
    container_name: ${APP_NAME}_wiki
    volumes:
      - "./data/wiki:/wiki/data"
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      - database
    networks:
      - wikijs

networks:
  wikijs:
    driver: bridge
